$engine: 3
$onesync: legacy
name: ESX Legacy
version: 0.1.2
author: ESX Framework
description: A full featured and highly configurable yet lightweight ESX Legacy base that can be easily extended. 

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/Sub-Zero-Interactive/PlumeESX-recipe
    ref: esx
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/loadingscreen
    dest: ./resources/loadingscreen
  
  # Download basic resources and ESX dependencies

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/bob74_ipl

  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    dest: ./tmp/esx
    
  - action: move_path
    src: ./tmp/esx/[esx]
    dest: ./resources/[esx]

  - action: move_path
    src: ./tmp/esx/[esx_addons]
    dest: ./resources/[esx_addons]
    
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: download_github
    src: https://github.com/EntityEvolution/ev-hud
    ref: main
    dest: ./resources/[hud]/ev-hud

  - action: download_github
    src: https://github.com/AvarianKnight/rp-radio
    ref: master
    dest: ./resources/rp-radio

  - action: connect_database
  - action: query_database
    file: ./tmp/esx/[SQL]/legacy.sql

  - action: download_file
    path: ./tmp/files/oxmysql-1.9.3.zip
    url: https://github.com/overextended/oxmysql/releases/download/v1.9.3/oxmysql-v1.9.3.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql-1.9.3.zip
    
  ## Patching configs: HUD 
  - action: replace_string
    file: ./resources/[esx]/es_extended/config.lua
    search: 'Config.EnableHud            	= true -- enable the default hud? Display current job and accounts (black, bank & cash)'
    replace: 'Config.EnableHud            	= false -- enable the default hud? Display current job and accounts (black, bank & cash)'

  - action: replace_string
    file: ./resources/[hud]/ev-hud/config/config.js
    search: 'Config.useFramework = false // Set to true to use ESX, VRP or QBCore'
    replace: 'Config.useFramework = true // Set to true to use ESX, VRP or QBCore'
  
  ## Patching configs: rp-radio
  - action: replace_string
    file: ./resources/rp-radio/config.lua
    search: |
      Name = "INPUT_REPLAY_START_STOP_RECORDING_SECONDARY", -- Control name"
    replace: | 
      Name = "INPUT_SELECT_CHARACTER_MICHAEL", -- Control name"
  - action: replace_string
    file: ./resources/rp-radio/config.lua
    search: 'Key = 289, -- F2'
    replace: 'Key = 166, -- F5'

  - action: replace_string
    mode: all_vars
    file: 
    - ./resources/loadingscreen/config.js

  ## Cleanup
  - action: remove_path
    path: ./tmp
  - action: remove_paths
    path: ./resources/esx_example
  - action: remove_path
    path: ./resources/[esx_addons]/esx_whitelist
  - action: remove_path
    path: ./resources/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[esx_addons]/esx_phone