$engine: 3
$onesync: legacy
name: ESX Legacy
version: 4.0.0
author: Tabarra & SaltySea & ESX Team
description: A full featured and highly configurable yet lightweight ESX Legacy base that can be easily extended. 

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/Sub-Zero-Interactive/PlumeESX-recipe
    ref: esx
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/loadingscreen
    dest: ./resources/loadingscreen
  
  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    dest: ./temp/esx
    
  - action: move_path
    src: ./tmp/esx/[esx]
    dest: ./resources/[esx]

  - action: move_path
    src: ./tmp/esx/[esx_addons]
    dest: ./resources/[esx_addons]
    
  - action: connect_database
  - action: query_database
    file: ./tmp/esx/[SQL]/legacy.sql

  - action: download_file
    path: ./tmp/files/oxmysql-1.9.3.zip
    url: https://github.com/overextended/oxmysql/releases/download/v1.9.3/oxmysql-v1.9.3.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql-1.9.3.zip
    
  ## Patching configs: multicharacter 
  - action: replace_string
    file: ./resources/[esx]/es_extended/config.lua
    search: 'Config.Multichar                = false -- Enable support for esx_multicharacter'
    replace: 'Config.Multichar                = true -- Enable support for esx_multicharacter'

  ## Cleanup
  - action: remove_path
    path: ./tmp
